[phases.setup]
aptPkgs = [
  "poppler-utils",
  "tesseract-ocr",
  "libmagic-dev",
]

[phases.install]
cmds = ["pip install --upgrade pip", "pip install -r requirements.txt"]

[start]
cmd = "uvicorn megaparse.api.main:app --host 0.0.0.0 --port $PORT"
